mysql:
    image: mysql
    environment:
        MYSQL_DATABASE: contao
        MYSQL_ROOT_PASSWORD: mypass
contao:
    image: pdir/contao-docker
    links: 
        - "mysql:mysql"
    ports:
        - "80:80"
    volumes:
        - ./workspace:/var/www/html/src:ro